const InfomationNavData = {
  sum: [
    "Offers - Information Technology",
    "Depreciation items",

    "Guides and articles",
    "AV Equipment",
    "Most Bought Top 50",
    " Computers used",
    " New arrivals",
    "To your doorstep in an hour",
  ],
  header: [
    "Computers",
    "Computer peripherals",
    "Computer components",
    "Network Devices",
    "Software and Licenses",
    "Office",
    "Digital gift cards",
  ],

  components: {
    Computers: [
      "Laptops",
      "Desktops",
      "Used Computers",
      "Computer Accessories",
      "Computer Services",
      "Servers",
    ],
    ComputerPeripherals: [
      "Monitors & Display Accessories",
      "Keyboards",
      "Mice",
      "Ergonomic mice and keyboards",
      "Printers & Printing Supplies",
      "Webcams",
      "External hard drives and storage",
      "Peripheral cables and adapters",
      "Docking stations and hubs",
      "Drawing Boards",
      "Payment systems and money processing",
    ],
    ComputerComponents: [
      "Graphics cards",
      "Processors",
      "Hard drives",
      "Motherboards",
      "RAM",
      "Cases",
      "Power supplies",
      "Installation and cooling",
      "Computer sound cards",
      "Computer component cables",
      "Single PCB Computers",
      "Optical drives",
    ],
    NetworkDevices: [
      "Routers and access points",
      "Ethernet network cables",
      "Modems",
      "NAS Network Disk Servers",
      "Network cards and network adapters",
      "Switches",
      "Firewalls",
      "Network Product Services and Service Extensions",
    ],
    SoftwareAndLicenses: [
      "Software for the office",
      "Licenses",
      "Photo and video editing software",
      "Security",
      "Operating systems",
      "Volume Licenses",
    ],
    Office: [
      "Office Technology",
      "Office furniture",
      "Office supplies",
      "Cleansing",
      "Batteries",
      "Cable management",
      "Calculators",
      "Writing and presentation boards",
      "Barcode Scanners",
      "Packaging Supplies",
    ],
  },
};

export default InfomationNavData;
