const searchSuggestions = [
  "iPhone 15",
  "Samsung Galaxy S24",
  "MacBook Air",
  "MacBook Pro",
  "Rog Ally Laptop",
  "Lenovo ThinkPad",
  "Dell XPS 13",
  "Sony Bravia TV",
  "LG OLED TV",
  "Samsung QLED TV",
  "Bose Headphones",
  "AirPods Pro",
  "Logitech Wireless Mouse",
  "Gaming Keyboard",
  "Mechanical Keyboard",
  "Running Shoes Nike",
  "Adidas Ultraboost",
  "Yoga Mat",
  "Dumbbell Set",
  "Electric Scooter",
  "Microwave Oven",
  "Air Fryer",
  "Coffee Maker",
  "Blender",
  "Electric Kettle",
  "Backpack",
  "Travel Bag",
  "Water Bottle",
  "Desk Lamp",
  "Office Chair",
  "Standing Desk",
  "Board Game Monopoly",
  "Lego Star Wars",
  "Pokemon Card Set",
  "Action Figure",
  "Toy Car",
  "Kids Puzzle",
  "Notebook",
  "Pen Set",
  "Printer",
  "Smartwatch",
  "Fitness Tracker",
  "Electric Toothbrush",
  "Hair Dryer",
  "Shaver",
  "Vacuum Cleaner",
  "Air Purifier",
  "Laptop Stand",
  "Monitor 27 inch",
  "External Hard Drive",
  "USB Flash Drive",
  "Router Wifi",
  "Bluetooth Speaker",
  "Portable Charger",
  "Camera DSLR",
  "Camera Lens",
  "Tripod",
  "Microphone",
  "Gaming Chair",
  "Projector",
  "Screen Protector",
  "Phone Case",
  "Tablet iPad",
  "Samsung Tablet",
  "Kindle E-reader",
  "Electric Grill",
  "Rice Cooker",
  "Juicer",
  "Food Processor",
  "Wine Glass",
  "Coffee Beans",
  "Espresso Machine",
  "Water Filter",
  "Helmet Bike",
  "Skateboard",
  "Scooter Kids",
  "Basketball",
  "Soccer Ball",
  "Tennis Racket",
  "Fishing Rod",
  "Camping Tent",
  "Sleeping Bag",
  "Hiking Shoes",
  "Winter Jacket",
  "Raincoat",
  "Sneakers",
  "Sandals",
  "Boots",
  "Jeans",
  "T-Shirt",
  "Dress",
  "Blouse",
  "Skirt",
  "Watch",
  "Sunglasses",
  "Wallet",
  "Backpack Travel",
  "Makeup Kit",
  "Perfume",
  "Skincare Set",
  "Hair Straightener",
  "Hair Curler",
  "Notebook Paper",
  "Pen Gel",
  "Highlighter Set",
  "Sticky Notes",
  "Desk Organizer",
  "Chair Cushion",
];
export default searchSuggestions;
